Working on frontend
aheacon/school_enrollment_frontend pull request #2
Opened 2024-02-17 18:20 UTC by Faariis

2024-02-20 16:21 UTC, aheacon commented on pages/api/auth/[...nextauth].js
> +        const res = await fetch("http://127.0.0.1:8000/api/teachers/login/", {
`constants.js` `url_base= http://127.0.0.1:8000/` -> poziv `$url_base`

2024-02-21 16:22 UTC, IsmetGlumcevic requested changes
package.json mora biti u prijektu kao i package-lock.json. 
package-lock.json se moze izbrisati prije nego sto se pokrene nmp i i onda ce se ponovo generisati.

2024-02-21 16:23 UTC, IsmetGlumcevic approved these changes
Meni lokalno ne radi prijava, vjerovatno jer je promjenjen and point za prijavu. Nemam lokalno postavljen BE nego korisitm live endpointe

2024-02-21 16:24 UTC, IsmetGlumcevic approved these changes
Izgleda dobro, prelazak na lokalni api

2024-02-21 16:27 UTC, IsmetGlumcevic approved these changes
Ako koristis vs code mozes instalirati Prettier - Code formatter i sa komandom shift+option+F formatiras code.

2024-02-21 16:27 UTC, IsmetGlumcevic approved these changes
Izgleda dobro.

2024-02-21 16:31 UTC, IsmetGlumcevic requested changes
Koliko vidim ovo je stranica za uredjivanje teachers. Trebalo bi napraviti da route bude malo specificniji npr pages/admin/editTeacher/[id].jsx. Mozda sada radi dobro ali kako budes dodavao vise stranica vjervotno ces imati vise dimacnih stranica a samo jedna dinamicna stranica moze biti u jednom levelu tj. folderu.

2024-02-21 16:38 UTC, IsmetGlumcevic approved these changes
Treba napraviti u .env NEXT_PUBLIC_URL variablu koja se koristi kroz citav projekat i pristupa se precess.env.NEXT_PUBLIC_URL

2024-02-27 14:34 UTC, IsmetGlumcevic reviewed
Please remove all console.log :)

2024-02-27 14:34 UTC, IsmetGlumcevic approved these changes

2024-03-08 09:39 UTC, aheacon requested changes
@Faariis  molim te squash sve ove commite u jedan commit, a u commit message napisi sve titlove ovih 17 commita, odnosno sta si sve uradio, pa da mergemo

2024-03-12 13:48 UTC, merged