Changed .env variables
aheacon/school_enrollment_frontend pull request #48
Opened 2024-05-20 20:49 UTC by Faariis

2024-05-21 03:43 UTC, aheacon commented
Ovo nije rjesenje i dalje ides na liveserver koji kada se pauzira frontend pukne.

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/8c02d9fd-436f-4a10-845b-7d2bf31854aa)

2024-05-21 03:51 UTC, aheacon requested changes

2024-05-21 03:51 UTC, aheacon commented on .env
> +APP_CONTAINER_NAME=myenrollment_container
Ne treba ti nista vezano za kontejner

2024-05-21 19:03 UTC, aheacon requested changes

2024-05-21 19:03 UTC, aheacon commented on constants.js
> +const Url = "http://127.0.0.1:3534/"
Zasto ovo ?

2024-05-21 21:28 UTC, Faariis commented on constants.js
> +const Url = "http://127.0.0.1:3534/"
Pa može na oba načina al ovo je da osiguram da se poziva http://127.0.0.1:3534/

2024-05-23 03:36 UTC, aheacon commented on constants.js
> +const Url = "http://127.0.0.1:3534/"
Ne moze na oba nacina, moze samo na jedan: **nema hard codiranja**

2024-05-23 03:37 UTC, closed without merging