Added pagination for listStudentsPerCourse
aheacon/school_enrollment_frontend pull request #74
Opened 2024-05-28 13:57 UTC by Faariis

- Added pagination just like in listStudents.js
- Added numbers and arrows
- Hid the pagination if there is no students

Closes #36

2024-06-03 04:03 UTC, aheacon requested changes
Opisi commit message bolje.

2024-06-03 04:03 UTC, aheacon commented on .env
> +NEXT_PUBLIC_URL=http://127.0.0.1:8000/
Ovo izbaci

2024-06-03 04:03 UTC, aheacon commented on package.json
> +  "packageManager": "yarn@4.2.2+sha512.c44e283c54e02de9d1da8687025b030078c1b9648d2895a65aab8e64225bfb7becba87e1809fc0b4b6778bbd47a1e2ab6ac647de4c5e383a53a7c17db6c3ff4b"
Ovo izbaci.

2024-06-03 04:03 UTC, aheacon commented on src/components/PDFcomponent/PDFdocument.js
> +  const firstPageStudents = students.slice(0, 22);
Ovo je opet hardcodirano.Ok za sad, ali napravi issue da popravimo

2024-06-04 13:19 UTC, Faariis commented on .env
> +NEXT_PUBLIC_URL=http://127.0.0.1:8000/
Izbacio sam

2024-06-04 13:19 UTC, Faariis commented on package.json
> +  "packageManager": "yarn@4.2.2+sha512.c44e283c54e02de9d1da8687025b030078c1b9648d2895a65aab8e64225bfb7becba87e1809fc0b4b6778bbd47a1e2ab6ac647de4c5e383a53a7c17db6c3ff4b"
Izbacio sam

2024-06-06 04:13 UTC, aheacon commented on src/components/PDFcomponent/PDFdocument.js
> +  const firstPageStudents = students.slice(0, 22);
@Faariis  uzmi molim te i ovaj commit https://github.com/aheacon/school_enrollment_frontend/pull/73 i stavi ga u ovaj PR  da mozemo zatvoriti #73. 
@kadusicadi nad #73 primijeni molim te zahtjevane promjene i nastavi raditi na ovoj grani zajedno sa Farisom.
Ovdje doradi backend tako da vrati @Faariis i `capacity` tako da ga moze koristiti genericki ovdje.

2024-06-06 04:16 UTC, aheacon commented on src/components/PDFcomponent/PDFdocument.js
> +  const numStudentsOnFirstPage = Math.min(27, acceptedStudents.length);
@kadusicadi ovdje bi mu trebao podatak za *trenutni smjer* koliko ima ukupno primljenih ucenika (`capacity` + `bezuslovni`). Ucenik generacije je dio `capacity`.

2024-06-06 04:17 UTC, aheacon commented on src/components/PDFcomponent/PDFdocument.js
> +  const numNonAcceptedPerPage = 27; //maybe 27
Ne vrsimo pretpostavke :).

2024-06-06 04:26 UTC, aheacon commented
@Faariis  molim te promijeni "Prikaz ucenika" na "Pronađi ucenika".
Imamo bug u admin panelu - ta opcija ne radi:
- Admin
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/924889dc-5e13-4a5e-b0af-70ec558325fe)

- Anonymous radi 
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/75734314-487d-43b1-aea2-93aa7c66b719)

Molim te popravi i to u ovom PR-u.

- Izbrisi molim te tacku iz footera

2024-06-06 04:34 UTC, aheacon commented
Dodatno
- Promijeni  molim te `title` (`Upis ucenika`)
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/2962cc55-8b45-41e9-99eb-807dc78e9a90)
- Izbrisi molim te tacku iz footera

2024-06-06 07:41 UTC, Faariis commented on src/components/PDFcomponent/PDFdocument.js
> +  const firstPageStudents = students.slice(0, 22);
Ovaj adijev dio koda je već dodan (commit 7)

2024-06-06 07:42 UTC, Faariis commented on src/components/PDFcomponent/PDFdocument.js
> +  const numStudentsOnFirstPage = Math.min(27, acceptedStudents.length);
Ovo što se tiče broja 27 je broj učenika koliko može stat na stranicu PFD-a da ne ide preko polja za direktoricu. Pošto ne planiram više mijenjati PDF ostat će 27.

2024-06-06 07:44 UTC, Faariis commented on src/components/PDFcomponent/PDFdocument.js
> +  const numNonAcceptedPerPage = 27; //maybe 27
Ma to sam kao komentar ostavio, jer sa trenutnim izlgedom tabele i dodatnim redom za VIII i IX morao sam smanjiti sa 28 na 27. Ostat će 27.

2024-06-08 03:45 UTC, merged

2024-06-08 04:36 UTC, aheacon commented
Docker pada
```bash
 => ERROR [frontend_app builder 7/7] RUN yarn build                                                                                                                                                    7.1s
------                                                                                                                                                                                                      
 > [frontend_app builder 7/7] RUN yarn build:                                                                                                                                                               
#0 0.757 yarn run v1.22.19                                                                                                                                                                                  
#0 0.815 $ next build                                                                                                                                                                                       
#0 2.032 Attention: Next.js now collects completely anonymous telemetry regarding usage.                                                                                                                    
#0 2.033 This information is used to shape Next.js' roadmap and prioritize features.                                                                                                                        
#0 2.033 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#0 2.033 https://nextjs.org/telemetry
#0 2.034 
#0 2.171   ▲ Next.js 14.2.3
#0 2.171   - Environments: .env
#0 2.171 
#0 2.172    Linting and checking validity of types ...
#0 6.973 
#0 6.973 Failed to compile.
#0 6.973 
#0 6.973 ./pages/admin/editTeacher/[id].jsx
#0 6.973 16:8  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 ./src/components/admin/editTeacher.js
#0 6.973 16:8  Warning: React Hook useEffect has a missing dependency: 'fetchTeacherData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 ./src/components/admin/newTeacher.js
#0 6.973 48:8  Warning: React Hook useEffect has a missing dependency: 'getSchool'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 ./src/components/home/listStudentsPerCourse.js
#0 6.973 39:6  Warning: React Hook useEffect has a missing dependency: 'getStudents'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 ./src/components/home/studentDetails.js
#0 6.973 98:8  Warning: React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 ./src/components/home/tableDetails.js
#0 6.973 104:6  Warning: React Hook useEffect has a missing dependency: 'fetchStudents'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 299:17  Error: Missing "key" prop for element in array  react/jsx-key
#0 6.973 
#0 6.973 ./src/components/layout/Layout.jsx
#0 6.973 49:41  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Use `<Image />` from `next/image` instead to utilize Image Optimization. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
#0 6.973 
#0 6.973 ./src/components/user/editStudent.js
#0 6.973 16:8  Warning: React Hook useEffect has a missing dependency: 'fetchStudentData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 ./src/components/user/gradePage.js
#0 6.973 106:6  Warning: React Hook useEffect has missing dependencies: 'fetchData' and 'fetchSpecialCourses'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 ./src/components/user/newStudent.js
#0 6.973 60:6  Warning: React Hook useEffect has a missing dependency: 'getSchool'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 ./src/components/user/studentAcknowledgments.js
#0 6.973 16:8  Warning: React Hook useEffect has a missing dependency: 'fetchStudentData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 ./src/components/user/studentTransition.js
#0 6.973 18:8  Warning: React Hook useEffect has a missing dependency: 'fetchStudentData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 6.973 
#0 6.973 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
#0 7.052 error Command failed with exit code 1.
#0 7.053 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

```